Карусель
js-tasks-ru/jsbasic-20210520_overhandz pull request #6
Opened 2021-06-01 19:32 UTC by Overhandz

2021-06-03 14:39 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-06-07 16:39 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-06-08 02:23 UTC, koalex requested changes
Тесты не проходят

2021-06-08 20:58 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2021-06-09 10:02 UTC, koalex approved these changes

2021-06-09 10:02 UTC, merged